title: William Anto
logo: 20250429_145508.jpg
description: Data Analyst with Two Years Experience in Report Automation using Advanced Excel, Data manipulation on SQL and Business Iterlligence Report on Power BI.
# show_download:true
#google_analytics:
theme: jekyll-theme-minimal
